name = "ark"
type = "javascript"  # ou "webpack", dependendo do seu setup

# Aqui está a configuração necessária para o Pages
[site]
bucket = "./dist"  # Ou o diretório onde os arquivos finais estão
entry-point = "."

# Adicione esta linha para o Pages reconhecer o diretório correto:
pages_build_output_dir = "./dist"  # Altere se necessário